config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'murmurs#index'
  get '/tops', to: 'tops#index'
  resources :murmurs do
    collection do
      post :confirm
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/murmur.rb
class Murmur < ApplicationRecord
  validates :content, length: { in: 1..140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :place, :about_me, :icon])
  end
end

app/controllers/murmurs_controller.rb
class MurmursController < ApplicationController
  before_action :set_murmur, only:[:show, :edit, :update, :destroy]

  def index
    @murmurs = Murmur.all
  end

  def new
    if params[:back]
      @murmur = Murmur.new(murmur_params)
    else
      @murmur = Murmur.new
    end
  end

  def create
    @murmur = Murmur.new(murmur_params)
    if @murmur.save
      redirect_to murmurs_path, notice: "Rubeet was successfully create."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @murmur.update(murmur_params)
      redirect_to murmurs_path, notice: "Rubeet was successfully edited."
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @murmur.destroy
    redirect_to murmurs_path, notice:"Rubeet was successfully destroyed."
  end

  def confirm
    @murmur = Murmur.new(murmur_params)
    render :new if @murmur.invalid?
  end

private

  def murmur_params
    params.require(:murmur).permit(:content)
  end

  def set_murmur
    @murmur = Murmur.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/murmurs_helper.rb
module MurmursHelper
  def choose_new_or_edit
    if action_name == 'new'||action_name == 'confirm'
      confirm_murmurs_path
    elsif action_name == 'edit'
      murmur_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <ul>
      <% if user_signed_in? %>
        <li class="a"><%= link_to 'Top', tops_path %></li>
        <li class="a"><%= link_to 'List', murmurs_path %></li>
        <li class="a"><%= link_to 'New', new_murmur_path %></li>
        <li class="a"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>
    </ul>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <p>DIC student test application　</p>
  </footer>
</html>

app/views/murmurs/_form.html.erb
<%= form_with(model: @murmur, local: true, url: choose_new_or_edit) do |form| %>
<% if @murmur.errors.any? %>
  <div id="error_explanation">
    <h2>There are <%= @murmur.errors.count %> errors(T T) </h2>

    <ul>
    <% @murmur.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>

<div class="field">
  <h4><%= form.label :content %></h4>
  <%= form.text_area :content %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/murmurs/confirm.html.erb
<h2>Send with the following contents.</h2>

<%= form_with(model: @murmur, url: murmurs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>


  <p>
    <strong>Content : </strong>
    <%= @murmur.content %>
  </p>

  <%= form.submit "Submit" %>
<% end %>

<br>

<%= form_with(model: @murmur, url: new_murmur_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "Back", name: 'back' %>
<% end %>

app/views/murmurs/edit.html.erb
<h1>Edit Rubeet</h1>

  <%= render 'form', murmur: @murmur %>

  <%= link_to 'Show', murmur_path %> |
  <%= link_to 'Back', murmurs_path %>

app/views/murmurs/index.html.erb
<section class="main-header">
  <% if current_user.try(:admin?) %>
    <h1>Rubeets_admin</h1>
  <% else %>
    <h1>Rubeet List</h1>
  <% end %>
</section>

<div class="list">
  <p id="notice"><%= notice %></p>

  <div>
    <table class="table">
      <tr>
        <th><h5>Content</h5></th>
      </tr>
    <% @murmurs.each do |murmur| %>
      <tr>
        <td><%= murmur.content %></td>
        <td><button type="button" class="btn btn-outline-warning"><%= link_to 'Show', murmur_path(murmur) %></button></td>
        <td><button type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_murmur_path(murmur) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to 'Destroy',murmur_path(murmur), method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/murmurs/new.html.erb
<section class="main-header">
  <h1>Rubeet</h1>
</section>

<div class="new">
  <br>

  <%= render 'form' %>

  <button type="button" class="btn btn-outline-info"><%= link_to 'Back', murmurs_path %></button>
</div>

app/views/murmurs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail</h1>

<p>
  <strong>Content:</strong>
  <%= @murmur.content %>
</p>

<%= link_to 'Edit', edit_murmur_path(@murmur) %>
<%= link_to 'Back', murmurs_path %>

app/views/tops/index.html.erb
<section class="main-header">
  <h1>Rubitter</h1>
</section>

<div class="about">
  <div>
  <h4>アプリ名の由来</h4>
  <h6>RubyでTwitterのcloneを作ったから。(安直w)</h6><br>
  </div>
  <br>
  <div>
  <h5>この演習を通して大切だと思ったこと</h5><br>
  <h6>つまずいたら初心に帰って、テキストをしっかり見直すこと。何かが抜けてたりする。<br>
  今日はここまで実装する、と決めたら意地でもやる。ど根性ぉぉ<br>
  こまめにメモしながらアウトプット。<br>
  自分が今何をしてるのか、なんでそのコードを書いてるのか、説明しながらやる感じで。<br>
  やることをメモし、順序立ててひとつずつ潰していく。</h6>
  </div>
</div>